CREATE TABLE [dbo].[Employees]
(
	[Id]			UNIQUEIDENTIFIER CONSTRAINT [DF_Employees_Id]  NOT NULL,
	[FirstName]		NVARCHAR (256) NOT NULL,
	[LastName]		NVARCHAR (256) NOT NULL,
	[CreatedOn]		DATETIME NOT NULL, 
	[CreatedBy]		NVARCHAR (50) NOT NULL,
	[UpdatedOn]		DATETIME NOT NULL, 
	[UpdatedBy]		NVARCHAR (50) NOT NULL,

	CONSTRAINT [PK_Employees] PRIMARY KEY ([Id])
);
