CREATE TABLE [dbo].[Employees]
(
	[Id]			UNIQUEIDENTIFIER CONSTRAINT [DF_Employees_Id] DEFAULT (NEWSEQUENTIALID()) ROWGUIDCOL NOT NULL,
	[FirstName]		NVARCHAR (256) NOT NULL,
	[LastName]		NVARCHAR (256) NOT NULL,
	[StatusId]		INT NOT NULL,
	[CreatedOn]		DATETIME NOT NULL, 
	[CreatedBy]		NVARCHAR (50) NOT NULL,
	[UpdateOn]		DATETIME NOT NULL, 
	[UpdatedBy]		NVARCHAR (50) NOT NULL,

	CONSTRAINT [PK_Employees] PRIMARY KEY ([Id])
);
